### ISSUE TITLE
RFC: JSON API Sparse Fieldsets

### ISSUE THREAD

**Issue by ADmad** [FriendsOfCake/crud-json-api#1]
_From @bravo-kernel on April 13, 2017 18:47_

The JsonApiListener is currently missing [JSON API Sparse Fieldsets](http://jsonapi.org/format/#fetching-sparse-fieldsets) functionality.

> A client MAY request that an endpoint return only specific fields in the response on a per-type basis by including a fields[TYPE] parameter.

```
GET /articles?include=author&fields[articles]=title,body&fields[people]=name HTTP/1.1
Accept: application/vnd.api+json
```

_Copied from original issue: FriendsOfCake/crud#521_

**Comment by bravo-kernel** [comment]
# Cash reward

I am awarding **$400** for the PR that adds "JSON:Sparse Fieldsets" (with test coverage) to crud-json-api.
