### ISSUE TITLE
Enhancement: Code 206 partial

### ISSUE THREAD

**Issue by dereuromark** [FriendsOfCake/crud-json-api#10]
Usually, when paginating rest pagination, those answer with a 200 code for a complete set, and 206 for partial results (multiple paginated result pages)
See https://www.artificialworlds.net/presentations/paging-in-a-rest-api/paging-in-a-rest-api.html
We could/should also do that maybe?

**Comment by bravo-kernel** [comment]
As far as I know there is no reference to code 206 in the JSON API specification. I also wasn't able to find anything in the neomerx/jsonapi repository, which basically is the reference I used whenever the spec was unclear to me.

I am not opposed to making improvements but I think we must be very strict on following the spec. Ember Data for example, I am not sure on how that will respond to receiving 206's.

**Comment by bravo-kernel** [comment]
I am closing this suggestion as I did not find anything related to partial results (in combination with JSON API). What I did find supports my earlier comment:

> I suspect the main reason the spec doesn't yet define conventions for partial success is that we don't yet support bulk operations. I.e., a request is always supposed to operate on only one resource at a time, and for operations on single resources, it's simpler if the operation must fail or succeed completely. 

>When we standardize the extension system + the bulk extension, support for things like this may get better. But, until then, I think you should try to restructure your resources so that one response code is sufficient. Again, if you post more about your particular data model, we can help further.

**Comment by dereuromark** [comment]
I think you misunderstand the http spec for "206 partial".
It just means that a resource like pagination is spred across more than just this one single page.
That's all. A basic API here can easily adhere to this without any issues.
This has nothing to do with failing or succeeding completely.

**Comment by bravo-kernel** [comment]
I'm not entirely convinced I am misinterpreting the spec https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/206. Just because pagination is spread across more than a single page does not mean it is related to ranges (they are simply different URLs with full range each, hence 200 status code).
