### ISSUE TITLE
Snake case attributes are converted to kebab case.

### ISSUE THREAD

**Issue by geoidesic** [FriendsOfCake/crud-json-api#103]
The standard for MySQL field/column names is to use snake-case – `my_field`. However, these names are converted to kebab-case in the JSONAPI response – `my-field`. Why?

It seems to only do this for root level attributes, not for nested attributes in JSON fields.

So for example a table with a column named "admin_contact" which is of data type `JSON` will be converted to "admin-contact" but it's children will not be converted. The output is thus:
```
{
    "data": {
        "type": "enquiries",
        "id": "2",
        "attributes": {
            "admin-contact": {
                "job_title": "hacker"
            }
        }
    }
}
```
This seems wrong to me. My front-end is expecting and sending snake-case, not kebab-case.

I tried changing the inflector via config in `routes.php`:
```
foreach (API_RESOURCES as $apiResource) {
      $routes->resources($apiResource, [
          'inflect' => 'underscore'
      ]);
  }
```

I tried both `underscore` and `tableize` but this made no difference, the output doesn't change. It doesn't seem to be picking up the config. I also tried setting the config in the `AppController::initialize` method but this caused an error: `Call to a member function config() on bool`. If I manually set the defaultConfig in the vendor class to `tableize` then it produces the expected output. So the issue is definitely that the config isn't being picked up.

**Comment by geoidesic** [comment]
I was able to solve this. Here are my notes:

1. Config passed to routes is ignored. The documentation shown here implies otherwise and is wrong: https://crud-json-api.readthedocs.io/en/latest/preface/setup.html#routing
1. Config can't be passed to the listener using the $components property, instead you have to do it in the controller's `initialize` method, like so:
```
public function initialize() {
	parent::initialize();
	$this->loadComponent('Crud.Crud', [
      		'actions' => [
			'Crud.Index',
		],
      		'listeners' => [
			'CrudJsonApi.JsonApi',
		]
    	]); 
    	$this->Crud->config(['listeners.jsonApi.inflect' => 'tableize']);
}
```

**Comment by geoidesic** [comment]
Argh... never mind. This is due to my schema having changed and me not updating the front-end code.

**Comment by geoidesic** [comment]
I think maybe this broke in the v4.0 conversion? It certainly doesn't work now. Previously (as indicated above) this issue was solved by use of `$this->Crud->config(['listeners.jsonApi.inflect' => 'tableize']);`. However, as of v4.0, `->config` is no longer a valid method. Instead one has to use `->setConfig`. 

Regardless. No matter what you set `inflect` to, it has no bearing on the output of root-level member names. These are automagically converted to kebab-case.

I'm not understanding why kebab-case is the standard. As far as I can see from the spec, the recommendation is camelCase: https://jsonapi.org/recommendations/#naming

I could be wrong but looking at the code I suspect this conversion is being done by NeoMerx. I'm not sure what the intended outcome for the `inflect` config setting for CrudJsonApi is but it definitely has no affect upon root-level member names.

Perhaps someone could elaborate on what it's intended to do? I'm not able to see any difference in output regardless of this config setting's value:- `camelize`, `dasherize`, `tableize` – it all generates the same output.

**Comment by geoidesic** [comment]
Yep, I've found the problem: https://github.com/FriendsOfCake/crud-json-api/blob/382907f1d9cca4fe23fc9113d93bb9ea45037806/src/Schema/JsonApi/DynamicEntitySchema.php#L160

There is no such view var `_inflect`; it's not set anywhere in this library, nor in `crud`, nor in `cake`. So either the documentation has missed explaining how to set this value or this value should be picked up from config, not view vars.

**Comment by geoidesic** [comment]
Looks like this can be set in AppController (really should be documented):
```
public function beforeRender(EventInterface $event)
    {
        if ($this->request->is('jsonapi')) {
            $this->set('_inflect', 'underscore');
        }
    }
```

**Comment by dakota** [comment]
> Looks like this can be set in AppController (really should be documented):
> 
> ```
> public function beforeRender(EventInterface $event)
>     {
>         if ($this->request->is('jsonapi')) {
>             $this->set('_inflect', 'underscore');
>         }
>     }
> ```

The documented method (using `setConfig('inflect', '')`) is correct for the latest version, however, looks like the `DynamicEntityClass` is still using the old version.

**Comment by dakota** [comment]
> I'm not understanding why kebab-case is the standard. As far as I can see from the spec, the recommendation is camelCase: [jsonapi.org/recommendations/#naming](https://jsonapi.org/recommendations/#naming)

At the time of this library originally being written, the JSON:API spec recommended kebab-case. A discussion for Ember: https://github.com/emberjs/data/issues/3416, You can also see it in the original v1.0 spec: https://jsonapi.org/format/#document-compound-documents, and the PR that made the change from kebab to camel: https://github.com/json-api/json-api/pull/1297

Since the current 1.0-beta is based on the new 1.1 JSON:API spec, it makes sense to change the default to be camelCase. I will do that, and fix the above issue.

**Comment by dakota** [comment]
I won't make it do deeply nested inflections, that is a fairly large rabbit hole. If you wish to have deeply nested inflection, then I would suggest creating your own `DynamicEntitySchema` that can traverse your deep structures.

**Comment by geoidesic** [comment]
That's fine. I'm actually trying to get it NOT to inflect. The problem I have is that it is by default inflecting all root-level attribute keys to `dasherize`.

**Comment by dakota** [comment]
Once I've done the fix, you'll just be able to set the `inflect` option to false.

**Comment by dakota** [comment]
@geoidesic Please test the latest dev (`cake-4.x` branch). The default should now be camelBacked, and the `inflect` option should now work as expected.
