### ISSUE TITLE
Javascript empty objects are being converted to empty arrays

### ISSUE THREAD

**Issue by geoidesic** [FriendsOfCake/crud-json-api#104]
I'm storing JSON objects to MySQL. Some of these objects are empty but it's important to the front end that I be able to store objects and they should stay as objects, not become arrays.

I tried using the Listener Option: `JSON_FORCE_OBJECT`, but this isn't helpful because it converts ALL arrays to objects. I need both arrays and objects. I just want them unadulterated.

I can see that the conversion is happening at the Cake code level (i.e. it's not MySQL nor the front-end doing the conversion).

How can I prevent this from happening?

i.e. I want to be able to store this to the database as is:
```
{AO: {}}
```
What's happening currently is that it is storing this instead:
```
{AO: []}
```
This breaks my app.

**Comment by geoidesic** [comment]
Turns out this is due to PHP, not CakePHP. PHP's `json_decode` converts objects to associative arrays. Normally this isn't a problem because `json_encode` turns associative arrays back into objects. However it doesn't do this for empty arrays because it doesn't know whether an empty array is associative or not.

So what would be helpful here is the ability to use a custom function instead of `json_decode` (because json_decode does a shitty job of it). 

I get the feeling no-one is maintaining this library?

**Comment by geoidesic** [comment]
Also JsonApiListener code should be updated to use middleware: https://book.cakephp.org/3/en/controllers/middleware.html#body-parser-middleware

**Comment by bravo-kernel** [comment]
@geoidesic I think it is only fair to let you (and future visitors) know that at least I will not be maintaining this library anymore. Life (and work) has led me into a different area altogether but... perhaps some friends member of even you could update it. Shouldn't be too hard. ❤️
