### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by igorfelluga** [FriendsOfCake/crud-json-api#115]
Hi
my is a question not a issue.
How can I do two validations? One for jsonapi calls and other for simple html form.
My doubt is about date, for jsonapi I have ISO date in the form dd/mm/yyyy format.
Thanks

**Comment by dakota** [comment]
Hi,

You can use the `saveOptions` config as described in the Crud documentation (https://crud.readthedocs.io/en/latest/actions/add.html#saveoptions)
