### ISSUE TITLE
Why are integer ids converted to strings in relationships (but not elsewhere)?

### ISSUE THREAD

**Issue by geoidesic** [FriendsOfCake/crud-json-api#124]
Given an entity `enquiry` which is related to `person` via `person_id` column. When storing a new `enquiry` the related `person_id` is stored to the database as an integer. In the JSONAPI return, any `attributes` that are integer values will be returned as Integer type, however relationships will return integer ids as String type.

Is this necessary due to the JSONAPI spec? 

To my mind it's a bug because you should not lose type information where it's possible to retain it.

**Comment by geoidesic** [comment]
Any idea whether this is handled by `crud-json-api` or `neomerx`? I'm wondering if this issue is on the correct repo.

**Comment by dakota** [comment]
The type casting is done by `crud-json-api` as it is enforced by the `neomerx` interfaces. The reason is that the  JSON:API spec explicitly requires `id` [to be string](https://jsonapi.org/format/1.1/#document-resource-object-identification).
