### ISSUE TITLE
Prefix routes should have an option to leave off the prefix from links

### ISSUE THREAD

**Issue by geoidesic** [FriendsOfCake/crud-json-api#126]
So here's an example of why this is useful. I have a front-end using axios which sets the base URL of the api to the prefix path. If the links contain the prefix path, then when following them from the front-end using that axios config, I end up with malformed URLs because the `api` portion is duplicated.

**Comment by dakota** [comment]
I don't think this is possible given how CakePHP routing works. When generating the url string, the router expects the prefix that the route was created with.

What we do in our front-end application, is if the url starts with the axios base url, then strip it off.

https://github.com/redux-json-api/redux-json-api/blob/master/src/jsonapi.js#L231-L243
