### ISSUE TITLE
`beforePaginate` hook triggers on `self` link but not on `related` link

### ISSUE THREAD

**Issue by geoidesic** [FriendsOfCake/crud-json-api#136]
`http://{{domain}}/api/enquiries/5/clients` will trigger `beforePaginate` but not `beforeFind` hook.
`http://{{domain}}/api/enquiries/5/relationships/clients` will trigger `beforeFind` but not `beforePaginate` hook.

This may be because the first one is being handled by `crud` and the other by `crud-json-api`. It seems to me though that the hook life-cycle should be consistent across these URLs for DRY reasons. I think the reason this happens is that `crud-json-api` maps `beforePaginate` to `beforeFind`, which is perhaps a bad idea, maybe instead it should proxy, rather than remap.

**Comment by dakota** [comment]
That behaviour is correct. `relationships` endpoints don't paginate, and so it doesn't make any sense for them to call `beforePaginate`.
