### ISSUE TITLE
`filter` queryString is not being respected

### ISSUE THREAD

**Issue by geoidesic** [FriendsOfCake/crud-json-api#137]
Given a URL like `http://{{domain}}/api/enquiryContacts?filter[role_id]=3&`
or `http://{{domain}}/api/enquiryContacts?filter[id]=1`

With the `friendsofcake/search` behaviour loaded for the `EnquiriesContacts` table:
```
class EnquiryContactsTable extends Table
{
    public function initialize(array $config): void
    {
        parent::initialize($config);
        $this->addBehavior('Search.Search');
     }
    
    public function searchManager(): \Search\Manager
    {
        $searchManager = $this->behaviors()->Search->searchManager();
        $searchManager->like('name', [
            'before' => true,
            'after' => true,
            'fields' => [$this->aliasField('name')],
        ]);

        return $searchManager;
    }
```
And the filter appearing in the query object's `extraOptions`:
```
Cake\ORM\Query Object
(
    [extraOptions] => Array
        (
            [collection] => default
            [search] => Array
                (
                    [filter] => Array
                        (
                            [role_id] => 3
                        )
                )
        )
    [repository] => App\Model\Table\EnquiryContactsTable Object
        (
            [registryAlias] => EnquiryContacts
            [table] => enquiry_contacts
            [alias] => EnquiryContacts
            [entityClass] => App\Model\Entity\EnquiryContact
            [associations] => Array
                (
                    [0] => Enquiries
                    [1] => People
                    [2] => Roles
                )

            [behaviors] => Array
                (
                    [0] => Timestamp
                    [1] => Search
                )

            [defaultConnection] => default
            [connectionName] => default
        )
```
The results returned are not respecting the filter query string.

Looking at the docs: https://crud-json-api.readthedocs.io/en/latest/api-usage-advanced/filtering.html
it seems like there isn't docs on how to differentiate filters – it only talks about `?filter=<someString>` not `?filter[role_id]=<someString>`

**Comment by dakota** [comment]
You need to include the `CrudJsonApi.Search` listener in your controller. I thought the documentation was updated for this, but I see now that it is not.

**Comment by geoidesic** [comment]
Ok that works for attributes but not for relationships.
E.g. if `PeopleTable` has association...
```
$this->belongsTo('Roles', [
            'foreignKey' => 'role_id',
        ]);
```
and `RolesTable` has:
```
$this->hasMany('People', [
            'foreignKey' => 'role_id',
        ]);
```
This doesn't work:
`http://{{domain}}/api/people?filter[role_id]=3`

With searchManager config:
```
$searchManager->like('role_id', [
            'before' => true,
            'after' => true,
            'fields' => [$this->aliasField('role_id')],
        ]);
```

**Comment by dakota** [comment]
Where is that filter declared? CrudJsonApi only does a `find('search')` on the primary table, it is up to the developer to implement any custom deep filtering rules.

**Comment by geoidesic** [comment]
What also looks odd (not sure if it's wrong) is that the links on these filter URL's are coming out with HTMLentities:

e.g.
```
"links": {
        "self": "/api/people?page=1&filter%5Bname%5D=George",
        "first": "/api/people?page=1&filter%5Bname%5D= George",
        "last": "/api/people?page=1&filter%5Bname%5D= George"
    },
```

**Comment by geoidesic** [comment]
> Where is that filter declared? CrudJsonApi only does a `find('search')` on the primary table, it is up to the developer to implement any custom deep filtering rules.

I'm not sure. I thought the searchManager config I showed above would be sufficient.
Where / how should it be declared? Are relationship id's considered `deep filtering`?

I'm trying to use `filter` by relationship id because I can't get relationships to respect `conditions` (as per #135). So at this stage I have no way of actually getting related results for a `belongsToMany` association that uses `conditions` to differentiate groups of records in a pivot table.

**Comment by dakota** [comment]
Those links are correct, they are urlencoded.

Where is the searchManager config (i.e. what table?). Depends on where the relationship id is, and where the searchManager config is on it being a deep filter. To me, a deep filter is anything that is not in the current table.

**Comment by geoidesic** [comment]
The searchManager config is on the `PeopleTable`. I tried this and it seems to work:
```
$searchManager->like('role_id', [
            'beforeProcess' => function (\Cake\ORM\Query $query, array $args, \Search\Model\Filter\Base $filter) {
                $query->contain('Roles');
            }
        ]);
```
Is that the right way?

**Comment by geoidesic** [comment]
Looks ok with `value` instead of `like`.

**Comment by dakota** [comment]
Sorry, I shouldn’t picked that up. Newer versions of MySQL (and I’m sure other DBMS) don’t allow `like` on integer fields
