### ISSUE TITLE
Problem with Has Many associations primary key

### ISSUE THREAD

**Issue by igorfelluga** [FriendsOfCake/crud-json-api#138]
Hi 
I got this problem when I save a record with has many associations, my table not use standard primary key "id" because I found it like this :(.
I found the problem in src/Listener/JsonApiListener.php, line 219 and 222
`            $query = $hasManyTable->find()
                ->select(['id'])
                ->where([
                    $entityForeignKey => $primaryResourceId,
                    'id IN' => $hasManyIds,
                ]);`
I fixed like this
`            $query = $hasManyTable->find()
                ->select([$hasManyTable->getPrimaryKey()])
                ->where([
                    $entityForeignKey => $primaryResourceId,
                    $hasManyTable->getPrimaryKey().' IN' => $hasManyIds,
                ]);`

**Comment by dakota** [comment]
Hi, would you be able to submit a pull request?

**Comment by igorfelluga** [comment]
No sorry

**Comment by dakota** [comment]
Fixed
