### ISSUE TITLE
array_key_exists is deprecated

### ISSUE THREAD

**Issue by geoidesic** [FriendsOfCake/crud-json-api#150]
JsonApiListener uses this deprecated method, which will throw errors / warnings.

**Comment by dakota** [comment]
As far as I can tell `array_key_exists` isn't deprecated? Do you have a link to where the deprecation is documented?

**Comment by geoidesic** [comment]
https://www.php.net/manual/en/migration74.deprecated.php

Looks like it is not completely deprecated, only for use with objects. Maybe not a necessary change then?

However, the reason I made this PR was because I was seeing the warnings pop up when using JsonApiListener with PHP 7.4

**Comment by ADmad** [comment]
The testsuite is now run for up to PHP 8.1 as part of CI and there are no warnings reported.
