### ISSUE TITLE
RFC: JSON API Multiple Field Sorting

### ISSUE THREAD

**Issue by ADmad** [FriendsOfCake/crud-json-api#2]
## Update 2018-03: fully implemented

---

_From @bravo-kernel on April 13, 2017 18:52_

The JsonApiListener currently does not fully support [JSON API Sorting](http://jsonapi.org/format/#fetching-sorting) functionality:

- [X] single field sorting (works)
- [ ] multi field sorting (not working)

> A server MAY choose to support requests to sort resource collections according to one or more criteria (“sort fields”).

```
GET /people?sort=age,name HTTP/1.1
Accept: application/vnd.api+json
```

_Copied from original issue: FriendsOfCake/crud#522_

**Comment by ADmad** [comment]
_From @bravo-kernel on April 14, 2017 8:17_

## Single field sorting (works)

Results can be sorted using the `sort` query parameter as can be seen in the following sorted JSON API produced by connecting to `http://cake3api.app/api/cocktails?sort=name`:

```json
{
  "data": [
    {
      "type": "cocktails",
      "id": "8",
      "attributes": {
        "name": "Black Velvet",
        "description": "Beer based",
        "created": "2015-04-11T09:52:02+00:00",
        "modified": null
      },
      "links": {
        "self": "/api/cocktails/8"
      }
    },
    {
      "type": "cocktails",
      "id": "7",
      "attributes": {
        "name": "Bloody Mary",
        "description": "Vodka based",
        "created": "2015-04-11T09:52:02+00:00",
        "modified": null
      },
      "links": {
        "self": "/api/cocktails/7"
      }
    },
    {
      "type": "cocktails",
      "id": "15",
      "attributes": {
        "name": "Boxer",
        "description": "Whiskey based",
        "created": "2015-04-11T09:52:03+00:00",
        "modified": null
      },
      "links": {
        "self": "/api/cocktails/15"
      }
    }
  ]
}
```

**Comment by ADmad** [comment]
_From @bravo-kernel on April 14, 2017 8:29_

To manipulate the direction in which results are sorted use the `direction` parameter. E.g.

```
http://cake3api.app/api/cocktails?sort=name&direction=desc
```

**Comment by ADmad** [comment]
_From @dakota on April 14, 2017 8:46_

Might want to look at implementing a jsonapi middleware eventually to map cakephp pagination and sorting into JSONAPI standard.

**Comment by ADmad** [comment]
_From @bravo-kernel on April 14, 2017 11:20_

## Multiple field sorting (not working)

It seems CakePHP currently does not support sorting on multiple fields. However, things might change. 

- https://github.com/cakephp/cakephp/issues/10028#issuecomment-272812357
- https://github.com/cakephp/cakephp/pull/9791
- https://github.com/cakephp/cakephp/issues/7324

**Comment by ADmad** [comment]
_From @dakota on April 14, 2017 16:10_

Luckily multiple field sorting is optional in the spec :)

**Comment by ADmad** [comment]
_From @bravo-kernel on April 14, 2017 18:39_

Indeed, I should read more carefully ;)

**Comment by bravo-kernel** [comment]
# Cash reward

I am awarding **$600** for the PR that adds "JSON:API Multi Field Sorting" (with test coverage) to crud-json-api.

**Comment by bravo-kernel** [comment]
Mr. @rchavik I can come up with two things reading the ticket carefully

1. ~the `direction` query param (which is most likely already functioning)~
2. the JSON:API pagination results

I can imagine getting two pages of results using your "sort". The links inside meta would currently (probably) not point to the correct next page. Unsure how this should be done technically but I can imagine the the query parameters must somehow be retained.

If I am overlooking something please let me know.

**Comment by bravo-kernel** [comment]
I see you have followed the JSON:API specification for sorting, awesome!

> The sort order for each sort field MUST be ascending unless it is prefixed with a minus (U+002D HYPHEN-MINUS, “-“), in which case it MUST be descending.
