### ISSUE TITLE
Error: [Crud\Error\Exception\MissingListenerException] Could not find listener class: 

### ISSUE THREAD

**Issue by ghost** [FriendsOfCake/crud-json-api#20]
I am using cakephp3 + friendsofcake/crud-json-api, but I got this error and was stuck here.

```php
2017-11-24 03:31:53 Error: [Crud\Error\Exception\MissingListenerException] Could not find listener class: 
Request URL: /banks
Stack Trace:
#0 /Users/ericgao/Sites/test/services/api-service/vendor/friendsofcake/crud/src/Controller/Component/CrudComponent.php(642): Crud\Controller\Component\CrudComponent->_loadListener('jsonapi')
#1 /Users/ericgao/Sites/test/services/api-service/vendor/friendsofcake/crud/src/Controller/Component/CrudComponent.php(201): Crud\Controller\Component\CrudComponent->_loadListeners()
#2 /Users/ericgao/Sites/test/services/api-service/vendor/cakephp/cakephp/src/Event/EventManager.php(416): Crud\Controller\Component\CrudComponent->beforeFilter(Object(Cake\Event\Event))
#3 /Users/ericgao/Sites/test/services/api-service/vendor/cakephp/cakephp/src/Event/EventManager.php(393): Cake\Event\EventManager->_callListener(Array, Object(Cake\Event\Event))
#4 /Users/ericgao/Sites/test/services/api-service/vendor/cakephp/cakephp/src/Event/EventDispatcherTrait.php(110): Cake\Event\EventManager->dispatch(Object(Cake\Event\Event))
#5 /Users/ericgao/Sites/test/services/api-service/vendor/cakephp/cakephp/src/Controller/Controller.php(502): Cake\Controller\Controller->dispatchEvent('Controller.init...')
#6 /Users/ericgao/Sites/test/services/api-service/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(114): Cake\Controller\Controller->startupProcess()
#7 /Users/ericgao/Sites/test/services/api-service/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(93): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\BanksController))
#8 /Users/ericgao/Sites/test/services/api-service/vendor/cakephp/cakephp/src/Http/BaseApplication.php(108): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#9 /Users/ericgao/Sites/test/services/api-service/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#10 /Users/ericgao/Sites/test/services/api-service/vendor/cakephp/cakephp/src/Routing/Middleware/RoutingMiddleware.php(104): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#11 /Users/ericgao/Sites/test/services/api-service/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#12 /Users/ericgao/Sites/test/services/api-service/vendor/cakephp/cakephp/src/Routing/Middleware/AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#13 /Users/ericgao/Sites/test/services/api-service/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#14 /Users/ericgao/Sites/test/services/api-service/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php(95): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#15 /Users/ericgao/Sites/test/services/api-service/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#16 /Users/ericgao/Sites/test/services/api-service/vendor/cakephp/debug_kit/src/Middleware/DebugKitMiddleware.php(52): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#17 /Users/ericgao/Sites/test/services/api-service/vendor/cakephp/cakephp/src/Http/Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#18 /Users/ericgao/Sites/test/services/api-service/vendor/cakephp/cakephp/src/Http/Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#19 /Users/ericgao/Sites/test/services/api-service/vendor/cakephp/cakephp/src/Http/Server.php(81): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#20 /Users/ericgao/Sites/test/services/api-service/webroot/index.php(40): Cake\Http\Server->run()
#21 {main}


2017-11-24 03:31:53 Warning: Warning (512): Unable to emit headers. Headers sent in file=/Users/ericgao/Sites/test/services/api-service/vendor/cakephp/cakephp/src/Error/Debugger.php line=850 in [/Users/ericgao/Sites/test/services/api-service/vendor/cakephp/cakephp/src/Http/ResponseEmitter.php, line 48]
Request URL: /banks
Client IP: 127.0.0.1
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE/src/Error/BaseErrorHandler.php, line 153
Cake\Http\ResponseEmitter::emit() - CORE/src/Http/ResponseEmitter.php, line 48
Cake\Http\Server::emit() - CORE/src/Http/Server.php, line 106
[main] - ROOT/webroot/index.php, line 40



2017-11-24 03:31:53 Warning: Warning (2): Cannot modify header information - headers already sent by (output started at /Users/ericgao/Sites/test/services/api-service/vendor/cakephp/cakephp/src/Error/Debugger.php:850) in [/Users/ericgao/Sites/test/services/api-service/vendor/cakephp/cakephp/src/Http/ResponseEmitter.php, line 148]
Request URL: /banks
Client IP: 127.0.0.1
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE/src/Error/BaseErrorHandler.php, line 153
header - [internal], line ??
Cake\Http\ResponseEmitter::emitStatusLine() - CORE/src/Http/ResponseEmitter.php, line 148
Cake\Http\ResponseEmitter::emit() - CORE/src/Http/ResponseEmitter.php, line 54
Cake\Http\Server::emit() - CORE/src/Http/Server.php, line 106
[main] - ROOT/webroot/index.php, line 40



2017-11-24 03:31:53 Warning: Warning (2): Cannot modify header information - headers already sent by (output started at /Users/ericgao/Sites/test/services/api-service/vendor/cakephp/cakephp/src/Error/Debugger.php:850) in [/Users/ericgao/Sites/test/services/api-service/vendor/cakephp/cakephp/src/Http/ResponseEmitter.php, line 181]
Request URL: /banks
Client IP: 127.0.0.1
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE/src/Error/BaseErrorHandler.php, line 153
header - [internal], line ??
Cake\Http\ResponseEmitter::emitHeaders() - CORE/src/Http/ResponseEmitter.php, line 181
Cake\Http\ResponseEmitter::emit() - CORE/src/Http/ResponseEmitter.php, line 55
Cake\Http\Server::emit() - CORE/src/Http/Server.php, line 106
[main] - ROOT/webroot/index.php, line 40



2017-11-24 03:31:53 Warning: Warning (2): Cannot modify header information - headers already sent by (output started at /Users/ericgao/Sites/test/services/api-service/vendor/cakephp/cakephp/src/Error/Debugger.php:850) in [/Users/ericgao/Sites/test/services/api-service/vendor/cakephp/cakephp/src/Http/ResponseEmitter.php, line 181]
Request URL: /banks
Client IP: 127.0.0.1
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE/src/Error/BaseErrorHandler.php, line 153
header - [internal], line ??
Cake\Http\ResponseEmitter::emitHeaders() - CORE/src/Http/ResponseEmitter.php, line 181
Cake\Http\ResponseEmitter::emit() - CORE/src/Http/ResponseEmitter.php, line 55
Cake\Http\Server::emit() - CORE/src/Http/Server.php, line 106
[main] - ROOT/webroot/index.php, line 40
```

**Comment by bravo-kernel** [comment]
Do you have both `Api` and `JsonApi` listeners enabled? If so, this might be related to https://github.com/FriendsOfCake/crud/pull/457 and you can try disabling the `ApiListener` or add the fix as described in the PR to `CrudComponent`.

**Comment by ghost** [comment]
> Do you have both Api and JsonApi listeners enabled? 
How do I enable them? Are the codes below?

// Plugin::load('Crud');
// // Plugin::load('JsonApi');
// Plugin::load('CrudJsonApi');
Plugin::loadAll();

**Comment by bravo-kernel** [comment]
Can you show us the code where you enable `JsonApiListener`? Should look similar to:

```php
<?php
class AppController extends Controller {

  public function initialize()
  {
    $this->loadComponent('RequestHandler');
    $this->loadComponent('Crud.Crud', [
      'actions' => [
        'Crud.Index',
        'Crud.View'
      ],
      'listeners' => ['CrudJsonApi.JsonApi']
    ]);
  }
```

Also, when posting code examples please use php [syntax highlighting](https://help.github.com/articles/creating-and-highlighting-code-blocks/) so we can read your code more easily, thanks.

**Comment by ghost** [comment]
public function initialize()
    {
        parent::initialize();

        $this->loadComponent('RequestHandler');
        $this->loadComponent('Flash');

        $this->loadComponent('Crud.Crud', [
            'actions' => [
                'Crud.Index',
                'Crud.View',
                'Crud.Add',
                'Crud.Edit',
                'Crud.Delete'
            ],
            'listeners' => [
                'CrudJsonApi.JsonApi',
                'CrudJsonApi.Pagination', // Pagination != ApiPagination
                'Crud.ApiQueryLog'
            ]
        ]);


        $this->Crud->config(['listeners.jsonapi.exceptionRenderer' => 'App\Error\JsonApiExceptionRenderer']);

    }

**Comment by ghost** [comment]
Composer.json

{
    "name": "cakephp/app",
    "description": "CakePHP skeleton app",
    "homepage": "https://cakephp.org",
    "type": "project",
    "license": "MIT",
    "require": {
        "php": ">=5.6",
        "cakephp/cakephp": "3.5.*",
        "mobiledetect/mobiledetectlib": "2.*",
        "cakephp/migrations": "~1.0",
        "cakephp/plugin-installer": "~1.0",
        "josegonzalez/dotenv": "2.*",
        "friendsofcake/crud-json-api": "^0.2.0",
        "friendsofcake/search": "^4.1"
    },
    "require-dev": {
        "psy/psysh": "@stable",
        "cakephp/debug_kit": "~3.2",
        "cakephp/bake": "~1.1",
        "cakephp/cakephp-codesniffer": "^3.0"
    },
    "suggest": {
        "markstory/asset_compress": "An asset compression plugin which provides file concatenation and a flexible filter system for preprocessing and minification.",
        "dereuromark/cakephp-ide-helper": "After baking your code, this keeps your annotations in sync with the code evolving from there on for maximum IDE and PHPStan compatibility.",
        "phpunit/phpunit": "Allows automated tests to be run without system-wide install.",
        "cakephp/cakephp-codesniffer": "Allows to check the code against the coding standards used in CakePHP."
    },
    "autoload": {
        "psr-4": {
            "App\\": "src"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Test\\": "tests",
            "Cake\\Test\\": "./vendor/cakephp/cakephp/tests"
        }
    },
    "scripts": {
        "post-install-cmd": "App\\Console\\Installer::postInstall",
        "post-create-project-cmd": "App\\Console\\Installer::postInstall",
        "post-autoload-dump": "Cake\\Composer\\Installer\\PluginInstaller::postAutoloadDump",
        "check": [
            "@test",
            "@cs-check"
        ],
        "cs-check": "phpcs --colors -p --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests",
        "cs-fix": "phpcbf --colors --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests",
        "test": "phpunit --colors=always"
    },
    "prefer-stable": true
}

**Comment by ghost** [comment]
If I commented the code below from AppController.php, 
$this->Crud->config(['listeners.jsonapi.exceptionRenderer' => 'App\Error\JsonApiExceptionRenderer']);

1, this URL is working well,
https://secure.test.dev/services/v1/api/banks.json
2, but this URL still doesn't work,
https://secure.test.dev/services/v1/api/banks

**Comment by ghost** [comment]
![screen shot 2017-11-27 at 15 19 33](https://user-images.githubusercontent.com/9809680/33247906-754ecaec-d386-11e7-8ea1-717c5af5fdcb.png)
I guess the problem might be that because my project automatically link to friendsofcake/crud and doesn't link to friendsofcake/crud-json-api, but I don't know how to fix it.

**Comment by bravo-kernel** [comment]
@ericgaonz were you able to resolve your issues?

**Comment by ericgaonz** [comment]
Thx for your help, yes, I fixed it through the change of Apache setting instead of change codes.
Just set my project as the document root then it worked.

DocumentRoot /var/www/public/public-api/public

**Comment by ghost** [comment]
Thx for your help, yes, I fixed it through the change of Apache setting instead of change codes.
Just set my project as the document root then it worked.

DocumentRoot /var/www/public/public-api/public

**Comment by bravo-kernel** [comment]
Thanks for confirming, good luck with your API 👍
