### ISSUE TITLE
ControllerTrait never execute controller action?

### ISSUE THREAD

**Issue by yusser** [FriendsOfCake/crud-json-api#22]
Hi,

i was debuging this plugin because my response alwayes return MissingTemplateException. I changed the order. First try component->execute and then controller action. 

        $component = $this->_isActionMapped();
        if ($component) {
            return $component->execute();
        }
        $callable = [$this, $request->params['action']];
        if (is_callable($callable)) {
            return call_user_func_array($callable, $request->params['pass']);
        }
       
Ps: I'm using cakephp 3.5.1 and json extension.

**Comment by bravo-kernel** [comment]
@yusser are you still experiencing this problem or were you able to resolve it?

**Comment by yusser** [comment]
Sorry, i made a mistake. 

The solution doesn't resolve the problem. I couldn't solve it. 
I give up looking for a solution and move on to another implementation. 

For some reason this puglin doesn't work on cakephp 3.5.1 or 
i just can not make it work (my limitations).

**Comment by bravo-kernel** [comment]
Sorry to hear that but thank you for closing the ticket.
