### ISSUE TITLE
[RFC] JSON:API Links

### ISSUE THREAD

**Issue by ADmad** [FriendsOfCake/crud-json-api#3]
_From @bravo-kernel on April 13, 2017 18:58_

The JsonApiListener is currently missing [JSON API Links](http://jsonapi.org/format/#document-links) functionality.

> Where specified, a links member can be used to represent links. The value of each links member MUST be an object (a “links object”)..

```json
"links": {
  "self": "http://example.com/posts"
}
```

```json
"links": {
  "related": {
    "href": "http://example.com/articles/1/comments",
    "meta": {
      "count": 10
    }
  }
}
```

_Copied from original issue: FriendsOfCake/crud#523_

**Comment by geoidesic** [comment]
I think this is already in place. Why is this still open? Or am I misunderstanding the issue?

**Comment by dakota** [comment]
This is now supported.
