### ISSUE TITLE
Schema is not registered for a resource at path ''

### ISSUE THREAD

**Issue by thiagoreri** [FriendsOfCake/crud-json-api#37]
I'm using this library and the following error is occurring in the title

**Comment by josegonzalez** [comment]
Can you provide the following information?

- cakephp version
- crud version
- crud-json-api version
- your `composer.json` file
- the url you are hitting that is returning this error
- The accompanying stacktrace - if any - for the error
- Any code related to the setup you did of this plugin.

**Comment by thiagoreri** [comment]
CakePHP 3.5.14
crud 5.3.3
crud-json-api 0.2.2

http://localhost:8765/api/v1/relacionamentos.json

Schema is not registered for a resource at path ''

```
$this->loadComponent('Crud.Crud', [
            'actions' => [
                'Crud.Index',
                'Crud.View',
                'Crud.Add',
                'Crud.Edit',
                'Crud.Delete'
            ],
            'listeners' => [
                'Crud.Api',
                'Crud.ApiPagination',
                'Crud.ApiQueryLog',
                'Crud.Search'
            ]
        ]);
```

**Comment by thiagoreri** [comment]
```
{
    "name": "cakephp/app",
    "description": "CakePHP skeleton app",
    "homepage": "https://cakephp.org",
    "type": "project",
    "license": "MIT",
    "require": {
        "php": ">=5.6",
        "cakephp/cakephp": "3.5.*",
        "cakephp/migrations": "^1.0",
        "cakephp/plugin-installer": "^1.0",
        "friendsofcake/crud": "^5.3",
        "friendsofcake/crud-json-api": "^0.2.2",
        "friendsofcake/search": "^4.3",
        "josegonzalez/dotenv": "2.*",
        "mobiledetect/mobiledetectlib": "2.*"
    },
    "require-dev": {
        "cakephp/bake": "^1.1",
        "cakephp/cakephp-codesniffer": "^3.0",
        "cakephp/debug_kit": "^3.2",
        "psy/psysh": "@stable"
    },
    "suggest": {
        "markstory/asset_compress": "An asset compression plugin which provides file concatenation and a flexible filter system for preprocessing and minification.",
        "dereuromark/cakephp-ide-helper": "After baking your code, this keeps your annotations in sync with the code evolving from there on for maximum IDE and PHPStan compatibility.",
        "phpunit/phpunit": "Allows automated tests to be run without system-wide install.",
        "cakephp/cakephp-codesniffer": "Allows to check the code against the coding standards used in CakePHP."
    },
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Test\\": "tests/",
            "Cake\\Test\\": "vendor/cakephp/cakephp/tests/"
        }
    },
    "scripts": {
        "post-install-cmd": "App\\Console\\Installer::postInstall",
        "post-create-project-cmd": "App\\Console\\Installer::postInstall",
        "post-autoload-dump": "Cake\\Composer\\Installer\\PluginInstaller::postAutoloadDump",
        "check": [
            "@test",
            "@cs-check"
        ],
        "cs-check": "phpcs --colors -p --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests",
        "cs-fix": "phpcbf --colors --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests",
        "test": "phpunit --colors=always"
    },
    "prefer-stable": true,
    "config": {
        "sort-packages": true
    }
}
```

**Comment by josegonzalez** [comment]
Can you show your `config/routes.php` and the `RelacionamentosController.php`?

**Comment by thiagoreri** [comment]
<?php

use Cake\Core\Plugin;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

Router::defaultRouteClass(DashedRoute::class);

Router::scope('/', function (RouteBuilder $routes) {
    $routes->connect('/', ['controller' => 'Pages', 'action' => 'display', 'home']);

    $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);

    $routes->fallbacks(DashedRoute::class);
});

Router::prefix('api/v1', function ($routes) {
    $routes->extensions(['json']);
    $routes->resources('Usuarios');
    $routes->resources('Relacionamentos');

    $routes->fallbacks(DashedRoute::class);
});

Plugin::routes();

**Comment by thiagoreri** [comment]
routes.php

<?php

use Cake\Core\Plugin;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

Router::defaultRouteClass(DashedRoute::class);

Router::scope('/', function (RouteBuilder $routes) {
    $routes->connect('/', ['controller' => 'Pages', 'action' => 'display', 'home']);

    $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);

    $routes->fallbacks(DashedRoute::class);
});

Router::prefix('api/v1', function ($routes) {
    $routes->extensions(['json']);
    $routes->resources('Usuarios');
    $routes->resources('Relacionamentos');

    $routes->fallbacks(DashedRoute::class);
});

Plugin::routes();

**Comment by thiagoreri** [comment]
routes.php

<?php

use Cake\Core\Plugin;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

Router::defaultRouteClass(DashedRoute::class);

Router::scope('/', function (RouteBuilder $routes) {
    $routes->connect('/', ['controller' => 'Pages', 'action' => 'display', 'home']);

    $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);

    $routes->fallbacks(DashedRoute::class);
});

Router::prefix('api/v1', function ($routes) {
    $routes->extensions(['json']);
    $routes->resources('Usuarios');
    $routes->resources('Relacionamentos');

    $routes->fallbacks(DashedRoute::class);
});

Plugin::routes();
?>

**Comment by thiagoreri** [comment]
RelacionamentosController.php

namespace App\Controller\Api\V1;

class RelacionamentosController extends AppController
{
    use \Crud\Controller\ControllerTrait;
}

**Comment by thiagoreri** [comment]
RelacionamentosTable.php

namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Relacionamento Model
 *
 * @method \App\Model\Entity\Relacionamentos get($primaryKey, $options = [])
 * @method \App\Model\Entity\Relacionamentos newEntity($data = null, array $options = [])
 * @method \App\Model\Entity\Relacionamentos[] newEntities(array $data, array $options = [])
 * @method \App\Model\Entity\Relacionamentos|bool save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Relacionamentos patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \App\Model\Entity\Relacionamentos[] patchEntities($entities, array $data, array $options = [])
 * @method \App\Model\Entity\Relacionamentos findOrCreate($search, callable $callback = null, $options = [])
 */
class RelacionamentosTable extends Table
{

    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $padrao = [
            'before' => true,
            'after' => true,
            'fieldMode' => 'OR',
            'comparison' => 'LIKE',
            'wildcardAny' => '*',
            'wildcardOne' => '?'
        ];

        $this->setTable('relacionamentos');
        $this->setDisplayField('id');
        $this->setPrimaryKey('id');

        $this->addBehavior('Search.Search');

        $searchManager = $this->behaviors()->Search->searchManager();
        $searchManager->like('filter', [
            'before' => true,
            'after' => true,
            'field' => [$this->aliasField('name')]
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->integer('id')
            ->allowEmpty('id', 'create');

        $validator
            ->scalar('numero')
            ->maxLength('numero', 6)
            ->requirePresence('numero', 'create')
            ->notEmpty('numero');

        return $validator;
    }
}

**Comment by thiagoreri** [comment]
AppController.php

namespace App\Controller\Api\V1;

use Cake\Controller\Controller;

class AppController extends Controller
{
    public function initialize()
    {
        parent::initialize();

        $this->loadComponent('RequestHandler');
        $this->loadComponent('Crud.Crud', [
            'actions' => [
                'Crud.Index',
                'Crud.View',
                'Crud.Add',
                'Crud.Edit',
                'Crud.Delete'
            ],
            'listeners' => [
                'CrudJsonApi.JsonApi',
                'CrudJsonApi.Pagination'
            ]
        ]);
    }
}

**Comment by thiagoreri** [comment]
RelacionamentosTable.php

<?php
namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Relacionamento Model
 *
 * @method \App\Model\Entity\Relacionamentos get($primaryKey, $options = [])
 * @method \App\Model\Entity\Relacionamentos newEntity($data = null, array $options = [])
 * @method \App\Model\Entity\Relacionamentos[] newEntities(array $data, array $options = [])
 * @method \App\Model\Entity\Relacionamentos|bool save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Relacionamentos patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \App\Model\Entity\Relacionamentos[] patchEntities($entities, array $data, array $options = [])
 * @method \App\Model\Entity\Relacionamentos findOrCreate($search, callable $callback = null, $options = [])
 */
class RelacionamentosTable extends Table
{

    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->setTable('relacionamentos');
        $this->setDisplayField('id');
        $this->setPrimaryKey('id');
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->integer('id')
            ->allowEmpty('id', 'create');

        $validator
            ->scalar('numero')
            ->maxLength('numero', 6)
            ->requirePresence('numero', 'create')
            ->notEmpty('numero');

        return $validator;
    }
}

**Comment by thiagoreri** [comment]
RelacionamentosTable.php

namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Relacionamento Model
 *
 * @method \App\Model\Entity\Relacionamentos get($primaryKey, $options = [])
 * @method \App\Model\Entity\Relacionamentos newEntity($data = null, array $options = [])
 * @method \App\Model\Entity\Relacionamentos[] newEntities(array $data, array $options = [])
 * @method \App\Model\Entity\Relacionamentos|bool save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Relacionamentos patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \App\Model\Entity\Relacionamentos[] patchEntities($entities, array $data, array $options = [])
 * @method \App\Model\Entity\Relacionamentos findOrCreate($search, callable $callback = null, $options = [])
 */
class RelacionamentosTable extends Table
{

    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->setTable('relacionamentos');
        $this->setDisplayField('id');
        $this->setPrimaryKey('id');
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->integer('id')
            ->allowEmpty('id', 'create');

        $validator
            ->scalar('numero')
            ->maxLength('numero', 6)
            ->requirePresence('numero', 'create')
            ->notEmpty('numero');

        return $validator;
    }
}

**Comment by thiagoreri** [comment]
RelacionamentosTable.php

`namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Relacionamento Model
 *
 * @method \App\Model\Entity\Relacionamentos get($primaryKey, $options = [])
 * @method \App\Model\Entity\Relacionamentos newEntity($data = null, array $options = [])
 * @method \App\Model\Entity\Relacionamentos[] newEntities(array $data, array $options = [])
 * @method \App\Model\Entity\Relacionamentos|bool save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Relacionamentos patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \App\Model\Entity\Relacionamentos[] patchEntities($entities, array $data, array $options = [])
 * @method \App\Model\Entity\Relacionamentos findOrCreate($search, callable $callback = null, $options = [])
 */
class RelacionamentosTable extends Table
{

    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->setTable('relacionamentos');
        $this->setDisplayField('id');
        $this->setPrimaryKey('id');
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->integer('id')
            ->allowEmpty('id', 'create');

        $validator
            ->scalar('numero')
            ->maxLength('numero', 6)
            ->requirePresence('numero', 'create')
            ->notEmpty('numero');

        return $validator;
    }
}`

**Comment by thiagoreri** [comment]
RelacionamentosTable.php

```php
use Cake\ORM\Table;
use Cake\Validation\Validator;

class RelacionamentosTable extends Table
{

    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->setTable('relacionamentos');
        $this->setDisplayField('id');
        $this->setPrimaryKey('id');
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->integer('id')
            ->allowEmpty('id', 'create');

        $validator
            ->scalar('numero')
            ->maxLength('numero', 6)
            ->requirePresence('numero', 'create')
            ->notEmpty('numero');

        return $validator;
    }
}

**Comment by thiagoreri** [comment]
routes.php

```php

use Cake\Core\Plugin;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

Router::defaultRouteClass(DashedRoute::class);

Router::scope('/', function (RouteBuilder $routes) {
    $routes->connect('/', ['controller' => 'Pages', 'action' => 'display', 'home']);

    $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);

    $routes->fallbacks(DashedRoute::class);
});

Router::prefix('api/v1', function ($routes) {
    $routes->extensions(['json']);
    $routes->resources('Usuarios');
    $routes->resources('Relacionamentos');

    $routes->fallbacks(DashedRoute::class);
});

Plugin::routes();

**Comment by thiagoreri** [comment]
AppController.php

```php
namespace App\Controller\Api\V1;

use Cake\Controller\Controller;

class AppController extends Controller
{
    public function initialize()
    {
        parent::initialize();

        $this->loadComponent('RequestHandler');
        $this->loadComponent('Crud.Crud', [
            'actions' => [
                'Crud.Index',
                'Crud.View',
                'Crud.Add',
                'Crud.Edit',
                'Crud.Delete'
            ],
            'listeners' => [
                'CrudJsonApi.JsonApi',
                'CrudJsonApi.Pagination'
            ]
        ]);
    }
}

**Comment by thiagoreri** [comment]
RelacionamentosController.php

```php
namespace App\Controller\Api\V1;

class RelacionamentosController extends AppController
{
    use \Crud\Controller\ControllerTrait;
}

**Comment by bravo-kernel** [comment]
In general, `Schema is not registered for a resource at path` is caused by a missing (related) Table or Entity. 

Are you sure:

- they exist (Entity and Table)
- for all related resources as well

**Comment by thiagoreri** [comment]
Error is this Schema is not registered for a resource at path ''

does not specify entity

Relacionamentos do not relate to anyone

```php
class RelacionamentosTable extends Table
{

    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->setTable('relacionamentos');
        $this->setDisplayField('id');
        $this->setPrimaryKey('id');
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->integer('id')
            ->allowEmpty('id', 'create');

        $validator
            ->scalar('numero')
            ->maxLength('numero', 6)
            ->requirePresence('numero', 'create')
            ->notEmpty('numero');

        return $validator;
    }
}

**Comment by bravo-kernel** [comment]
Does the Entity exist? Also can you share the stack trace as requested by @josediazgonzalez?

**Comment by thiagoreri** [comment]
Entity Relacionamentos.php


```php4

namespace App\Model\Entity;

use Cake\ORM\Entity;

/**
 * Relacionamento Entity
 *
 * @property int $id
 * @property string $numero
 */
class Relacionamentos extends Entity
{

    /**
     * Fields that can be mass assigned using newEntity() or patchEntity().
     *
     * Note that when '*' is set to true, this allows all unspecified fields to
     * be mass assigned. For security purposes, it is advised to set '*' to false
     * (or remove it), and explicitly make individual fields accessible as needed.
     *
     * @var array
     */
    protected $_accessible = [
        'numero' => true
    ];
}

**Comment by thiagoreri** [comment]
{
    "message": "Schema is not registered for a resource at path ''.",
    "url": "/api/v1/relacionamentos.json",
    "code": 500,
    "file": "D:\\Projetos\\PHP\\api-sistema\\vendor\\neomerx\\json-api\\src\\Encoder\\Parser\\Parser.php",
    "line": 282
}

**Comment by bravo-kernel** [comment]
I am pretty sure your Entity must be singular and is the problem here.

Could you try “baking” the entity?

**Comment by thiagoreri** [comment]
Uhuuu, thank you

**Comment by bravo-kernel** [comment]
No problem, good luck with your API!

**Comment by bravo-kernel** [comment]
If you want to help us, give this repo a star
