### ISSUE TITLE
Update for Cake 3.6

### ISSUE THREAD

**Issue by bravo-kernel** [FriendsOfCake/crud-json-api#38]
Like done here, https://github.com/ADmad/cakephp-sequence/pull/26

**Comment by francisreboucas** [comment]
Composer not install this package with cakephp 3.6.1

**Comment by E-P1983** [comment]
Yup, doesnt work on latest cakephp.

**Comment by bravo-kernel** [comment]
PR opened, feel free to help out. https://github.com/FriendsOfCake/crud-json-api/pull/49

**Comment by bravo-kernel** [comment]
CakePHP 3.6 support released as https://github.com/FriendsOfCake/crud-json-api/releases/tag/0.3.1
