### ISSUE TITLE
RFC: JSON API Filtering (search)

### ISSUE THREAD

**Issue by ADmad** [FriendsOfCake/crud-json-api#4]
_From @bravo-kernel on April 14, 2017 14:29_

[JSON API Filtering](http://jsonapi.org/format/#fetching-filtering) should be fully supported using the [FriendsOfCake Search Plugin](https://github.com/FriendsOfCake/search).

> The filter query parameter is reserved for filtering data. Servers and clients **SHOULD** use this key for filtering operations. 

Note: JSON API is **agnostic** about the strategies supported by a server. The filter query parameter can be used as the basis for any number of filtering strategies.

_Copied from original issue: FriendsOfCake/crud#524_

**Comment by ADmad** [comment]
_From @bravo-kernel on April 14, 2017 14:33_

I would prefer if a FoC member would close this issue after confirming but it looks like this is indeed fully supported by using:

- the [SearchListener](https://crud.readthedocs.io/en/latest/listeners/search.html)
- combined with a search alias named `filter` like show below

```php
    public function searchConfiguration()
    {
        $search = new Manager($this);
        $search
            ->like('filter', [
                'before' => true,
                'after' => true,
                'field' => [$this->aliasField('name'), $this->aliasField('description')]
            ]);

        return $search;
    }
```

Connecting to `http://cake3api.app/api/cocktails?filter=beer` filters the results like shown below:

```json
{
  "data": [
    {
      "type": "cocktails",
      "id": "8",
      "attributes": {
        "name": "Black Velvet",
        "description": "Beer based",
        "created": "2015-04-11T09:52:02+00:00",
        "modified": null
      },
      "links": {
        "self": "/api/cocktails/8"
      }
    }
  ]
}
```

**Comment by ADmad** [comment]
_From @bravo-kernel on April 18, 2017 14:25_

**Update:** adding an Ember Data generated URL with filtering which seems to match information about regarding JSON API filtering out there on the internet. Unsure if this can be matched using the Search plugin though.

    /user-profiles?filter[user_id]=1

Multiple filters seem to be possible as well:

```curl
GET https://example.com/api/v1/posts
    ?page[number]=2
    &page[size]=50
    &sort=author,-created
    &fields[posts]=id,title,created
    &include=comments,author
    &filter[posts]=1,2
    &filter[comments]=1,2
    &filter[status]=posted
```

**Comment by ADmad** [comment]
_From @dakota on April 18, 2017 14:53_

It can if a middleware is written to convert the nested form into a non nested form ☺️

**Comment by dereuromark** [comment]
One could also think about a http://graphql.org/ translation, or http://querybuilder.js.org/ etc.
Anything that can easily use a ?filter with all kind of =, !=, >=, <=, <, >, IN, NOT IN, RANGE etc.

**Comment by dereuromark** [comment]
But yeah, some basic converting from nested to non nested would be fine for now.
It will then only ever use "filter" key and not need any other query string keys.

**Comment by dakota** [comment]
Turns out that https://github.com/friendsofcake/search already handles conversion.

A request like `users?filter[id]=1` or `users?filter[id][]=1&filter[id][]=2` will be matched, and correctly searched by the following search config:

```php
        $manager
            ->value('filter.id', [
                'multiValue' => true,
                'field' => 'id'
            ]);
```

**Comment by bravo-kernel** [comment]
Closing as proof was added in #28.
