### ISSUE TITLE
"sort" not working with paginate['sortWhitelist']

### ISSUE THREAD

**Issue by brenoroosevelt** [FriendsOfCake/crud-json-api#52]
The controller:
```php
class ArticlesController extends AppController
{
    use ControllerTrait;

    public $paginate = [
       'sortWhitelist' => ['id','title']
    ];
}
```

- **Problem 1:** ```JsonApiListener``` ignores the ```paginate[sortWhitelist]``` and order anything.
```
GET /articles?sort=description
```
Should not order.

- **Problem 2:** When ```paginate['sortWhitelist']```  is set, the fields with descending order (with minus "-") disappear from links in top-level. the same error occurs with multiple sort fields.

```
GET /articles?sort=id,title    (Problem 2.a)
GET /articles?sort=-title      (Problem 2.b)
```
```json
{
  "links": {
        "self": "/articles?page=1",
        "first": "/articles?page=1",
        "last": "/articles?page=1",
        "prev": null,
        "next": null
    },
    "data" : [ ]
}
```
Pagination links not maintaining the ```sort``` query parameter: ```&sort=-title``` and ```&sort=id,title``` (when ```paginate['sortWhitelist']``` is set!)

- **Problem 3:** ```JsonApiListener``` never throws ```BadRequestException``` as necessary to the sort fields out of ```paginate['sortWhitelist']``` (Problem 3.a) .
Sort fields that does not exists in resource/relationships are responding with 500 Internal Server Error (sql error)... (Problem 3.b).

According JSON API (http://jsonapi.org/format/#fetching-sorting):
> If the server does not support sorting as specified in the query parameter sort, it MUST return 400 Bad Request.

**Proposal:**

- Create  a configuration ```sort.whitelist``` in ```JsonApiListener``` (like ```include.whitelist```). Merge with ```paginate[sortWhitelist]``` when necessary. This configuration can be used in ```view``` action to order included  relationships. 
- Check the requested sort parameter to validate.

**Comment by bravo-kernel** [comment]
This is a very good analysis @brenoroosevelt and it makes sense to me so feel free to propose a PR.

**Comment by brenoroosevelt** [comment]
I will try something.
Let me note another related problem:
- **Problem 4.**  Default ordering in pagination generates inconsistent links (independent of the whitelist)
```php
 public $paginate = [
       'order' => ['title' => 'desc']                   // Problem 4.a
    ];
```
```
GET /articles
```
```json
    "links": {
        "self": "/articles?page=1&sort=Articles.title",
        "first": "/articles?page=1&sort=Articles.title",
        "last": "/articles?page=1&sort=Articles.title",
        "prev": null,
        "next": null
    },
```
In this case (above), the links don't have the minus to indicate descending order.
```php
 public $paginate = [
       'order' => ['title' => 'desc', 'id' => 'asc']     // Problem 4.b
    ];
```
Default ordering with multi fields... the sort parameter disappear. 
```json
    "links": {
        "self": "/articles?page=1",
        "first": "/articles?page=1",
        "last": "/articles?page=1",
        "prev": null,
        "next": null
    },
```
I think default ordering should not appear on links.

**Comment by learntoswim** [comment]
I was having a similar problem as `Problem 4.b`, ended up changing the options as [noted in Cake's docs](https://book.cakephp.org/3.0/en/controllers/components/pagination.html#using-controller-paginate)

Before:

```php
    public $paginate = [
        'order' => [
            'date' => 'desc',
        ],
    ];
```

After:

```php
    public $paginate = [
        'sort' => 'date',
        'direction' => 'desc',
    ];
```

This now works as expected.

**Comment by dakota** [comment]
Closing as stale. Please reopen if this is still an issue.
