### ISSUE TITLE
Fatal Error JsonApiExceptionRenderer

### ISSUE THREAD

**Issue by davizxtr** [FriendsOfCake/crud-json-api#53]
I'm creating an api with jsonapi.

If the category I try to find exists there is no problem but if it does not exist it returns this error.
![image](https://user-images.githubusercontent.com/37248385/39432336-80e07d66-4c93-11e8-97b6-1a30fea21810.png)

I have this configuration in app.php:
![image](https://user-images.githubusercontent.com/37248385/39432351-8c6f3c26-4c93-11e8-93df-1e455717f759.png)

I have this configuration in appController.php:
![image](https://user-images.githubusercontent.com/37248385/39432184-1b21f9b4-4c93-11e8-945d-0efc824d0675.png)

and bootstrap
![image](https://user-images.githubusercontent.com/37248385/39432227-2e28bbd8-4c93-11e8-8259-232f0b84141a.png)

**Comment by bravo-kernel** [comment]
This is not a help-forum. Please read https://crud-json-api.readthedocs.io/en/latest/preface/setup.html#exception-handler carefully, then turn to the CakePHP Slack or IRC channels if you still need help.
