### ISSUE TITLE
Updating relationships

### ISSUE THREAD

**Issue by davizxtr** [FriendsOfCake/crud-json-api#54]
Hi.

I have problems updating relations with jsonapi.
I have published my doubts in slack and redirected me to the documentation.
https://github.com/FriendsOfCake/crud-json-api.

According to the documentation, this is the way to edit:
https://crud.readthedocs.io/en/4.4.4/listeners/jsonapi.html#http-patch-edit
```
{
  "data": {
    "type": "countries",
    "id": "10",
    "attributes": {
      "name": "My new name"
    }
  }
}
```

In the documentation I can not find how to edit a relationship.
According to the jsonapi guide, this is done:
http://jsonapi.org/format/#crud-updating-relationships
```
PATCH /articles/1
{
  "data": {
    "type": "articles",
    "id": "1",
    "relationships": {
      "author": {
        "data": { "type": "people", "id": "1" }
      }
    }
  }
}
```

In my case, I have a advert with a location
I tried the following but it does not work..
```
PATH http://www.cake3.local.com/api/adverts/93
{
  "data": {
    "type": "adverts",
    "id": "93",
    "relationships": {
      "location": {
        "data": { 
           "type": "locations", 
           "id": "71",
           "attributes": {
              "street": "new street"
           }
        }
      }
    }
  }
}
```

It does not return any error.
Directly gives me back information of advert.

Thanks.

**Comment by bravo-kernel** [comment]
It seems there is a working test for the add-action here. https://github.com/FriendsOfCake/crud-json-api/blob/master/tests/Fixture/JsonApi/post_country_multiple_relationships.json.

Please try that first. If it does not work for `PATCH`, feel free to add a test/PR.

**Comment by davizxtr** [comment]
Hi!

I have been doing tests with several relationships.
All relationships being with hasMany and belongsToMany.
It works well, the registry changes in database but the response of the api is not correct.
![image](https://user-images.githubusercontent.com/37248385/39885860-09400bac-548e-11e8-971e-3fb6689cf6f3.png)

Another user has already happened https://github.com/FriendsOfCake/crud-json-api/issues/23

I think I have the latest version in all the plugins
```
"php": ">=5.6",
        "cakephp/cakephp": "3.5.*",
        "mobiledetect/mobiledetectlib": "2.*",
        "cakephp/migrations": "~1.0",
        "cakephp/plugin-installer": "~1.0",
        "josegonzalez/dotenv": "2.*",
        "friendsofcake/bootstrap-ui": "^1.3",
        "davidyell/proffer": "^0.8.2",
        "friendsofcake/crud": "^5.0",
        "admad/cakephp-jwt-auth": "^2.2",
        "ozee31/cakephp-cors": "^1.1",
        "friendsofcake/crud-json-api": "^0.2.5"
```

Thanks.

**Comment by davizxtr** [comment]
I have both the entities and the tables created.
Entities with singular name and tables with plural.
If I do GET on a resource it brings the relationships correctly.
If I do PATH it updates in database correctly.
Only the response of the api gives error and only gives me error when I update a relation.

**Comment by davizxtr** [comment]
Tests with several relationships. The database is updated well but the response fails.
```
PATH http://www.cake3.local.com/api/adverts/93
{
    "data": {
        "type": "adverts",
        "id": "93",
        "attributes": {},
        "relationships": {
            "rates": {
                "data": [{
	                    "type": "rates",
	                    "id": "27",
	                    "attributes": {
	                    	"concepto": "test2",
	                    	"precio": "40"
	                    }
	             }]
            }
        }
    }
}
```

```
"errors": [
        {
            "code": "500",
            "title": "Internal Server Error",
            "detail": "Schema is not registered for a resource at path 'rates'."
        }
    ],
    "debug": {
        "class": "InvalidArgumentException",
        "trace": [
            {
                "file": "C:\\xampp\\htdocs\\cake3\\vendor\\neomerx\\json-api\\src\\Encoder\\Parser\\Parser.php",
                "line": 163,
                "function": "getSchema",
                "class": "Neomerx\\JsonApi\\Encoder\\Parser\\Parser",
                "type": "->",
                "args": [
                    {
                        "concepto": "test2",
                        "precio": "40",
                        "advert_id": 93,
                        "created": "2018-05-13T11:29:25+00:00",
                        "modified": "2018-05-13T11:29:25+00:00",
                        "id": 693
                    },
                    []
                ]
            },
            {
                "file": "C:\\xampp\\htdocs\\cake3\\vendor\\neomerx\\json-api\\src\\Encoder\\Parser\\Parser.php",
                "line": 185,
                "function": "parseData",
                "class": "Neomerx\\JsonApi\\Encoder\\Parser\\Parser",
                "type": "::",
                "args": []
            },
            {
                "file": "C:\\xampp\\htdocs\\cake3\\vendor\\neomerx\\json-api\\src\\Encoder\\Parser\\Parser.php",
                "line": 135,
                "function": "parseData",
                "class": "Neomerx\\JsonApi\\Encoder\\Parser\\Parser",
                "type": "::",
                "args": []
            },
```

**Comment by bravo-kernel** [comment]
Could you try disabling this line in `JsonApiListener` and see if the problem disappears?

```php
    $this->_insertBelongsToDataIntoEventFindResult($event);
```

**Comment by bravo-kernel** [comment]
First of all, after spending some time refactoring the tests I now see we need to work on `Updating Resources`/`PATCH`:

- proper tests are missing (currently only the HTTP Status Code is checked)
- test checking the JSON API response bodies are missing
- this is simply not under control enough

The good news is that I did manage to update a relationship directly, just like in your `rates` example. The only difference is that I did NOT include the `attributes` node for `rates`.

Tested on CakePHP 3.6 btw

**Comment by davizxtr** [comment]
disabling this line does not solve the problem
```
 $this->_insertBelongsToDataIntoEventFindResult($event);
```
For the second option. I have cake 3.5, how do I update cake 3.6? I make composer update to 3.6 and I get error
```
COMPOSER
"require": {
        "php": ">=5.6",
        "cakephp/cakephp": "3.6.*",
...
C:\xampp\htdocs\cake3>composer update
- friendsofcake/crud-json-api 0.2.5 requires cakephp/cakephp <3.6.0
```

**Comment by bravo-kernel** [comment]
did you run the upgrade as described in the Migration Guide, e.g.

> composer require --update-with-dependencies "cakephp/cakephp:3.6.*"

**Comment by davizxtr** [comment]
is it a good idea to uninstall the crud plugin? and reinstall it with version 3.6?

![image](https://user-images.githubusercontent.com/37248385/40325836-7256c498-5d3d-11e8-8c8f-dd3fb27fe586.png)

**Comment by bravo-kernel** [comment]
You could, same for crud-json-api. Upgrade cake and crud first, then re-install crud-json-api.

**Comment by davizxtr** [comment]
I have already been able to upgrade to cake 3.6 and the plugins also
```
"friendsofcake/crud": "^5.4",
"friendsofcake/crud-json-api": "^0.3.2"
```
I've tried an example of tag association.
Without attributes.
But still giving the same error...
![image](https://user-images.githubusercontent.com/37248385/40327097-fa5fe99c-5d41-11e8-9e63-b5100cbc9cac.png)

is it possible that with version 2 of neomerx be corrected?

**Comment by bravo-kernel** [comment]
Good that you are on 3.6 now. Before we move one:

Can you confirm updating a `belongsTo` relationships now works for you? There are two working fixtures for it [here](https://github.com/FriendsOfCake/crud-json-api/tree/master/tests/Fixture/JsonApiRequestBodies/UpdatingResources).

### Updating hasMany

Since the database is updated correctly you should start debugging from this line https://github.com/FriendsOfCake/crud-json-api/blob/master/src/Listener/JsonApiListener.php#L160 and see where the issue comes from. This seems unrelated to Neomerx 2.x.

**Comment by bravo-kernel** [comment]
This is also a good place to debug, the viewVars should contain the related data. If it is not there, debug from there.

https://github.com/FriendsOfCake/crud-json-api/blob/master/src/View/JsonApiView.php#L76

**Comment by bravo-kernel** [comment]
The source for this error is in `JsonApiView`. I have started a PR with an explanation of what goes wrong. If you want you can start looking from there.

https://github.com/FriendsOfCake/crud-json-api/blob/422ed2470dee95dd7068bcb5fbc72f1fc5fa54a0/src/View/JsonApiView.php#L126

My priorities are top-down atm: GET, POST then PATCH.

**Comment by bravo-kernel** [comment]
Thanks for reporting this, I have updated master to do the following:

- `belongsTo` relationships can be created/updated in a single POST/PATCH (as long as you use existing foreign keys)
- trying to create new (hasMany) relationships will now throw a BadRequestException (as side-posting is not supported by JSON API 1.0)

Would you mind trying out the master branch and see if this helps/answers your questions?

**Comment by bravo-kernel** [comment]
To keep things clean I have opened a new ticket purely for the implementation of PATCH with existing `hasMany` relationships, which is currently not implemented according to the spec. https://github.com/FriendsOfCake/crud-json-api/issues/73.

Feel free to comment there, help needed before I implement anyway.

**Comment by bravo-kernel** [comment]
**Setting** `belongsTo` and `hasMany` relationships has been added in [release 0.4.0](https://github.com/FriendsOfCake/crud-json-api/releases/tag/0.4.0)

Please note that updating attributes for a related resource (when patching the primary resource) will not work as this is not supported by the JSON API specification.
