### ISSUE TITLE
Listener configuration option `inflect` does not work

### ISSUE THREAD

**Issue by thiagoreri** [FriendsOfCake/crud-json-api#55]
API replace fields with '_' to '-'.

Why?

**Comment by bravo-kernel** [comment]
This is sort of a "legacy" bug. We implemented using recommended `dasherized` and never got around to fully implementing the `_`. For now two options:

- use `-`
- come up with a PR that will fully support [this `inflect` setting](https://github.com/FriendsOfCake/crud-json-api/blob/master/src/Listener/JsonApiListener.php#L61)

**Comment by thiagoreri** [comment]
I did not understand the second option. What should I do to use it?

**Comment by bravo-kernel** [comment]
Basically that setting does NOT work (everything is currently `dasherized`). If you want to make `underscored` work, you will need to fix the code and create a PR.

**Comment by thiagoreri** [comment]
Okay, so should I ignore the CakePHP field naming conventions and adopt the camelCase pattern?

first_name to firstName

first-name in javascript does not work

**Comment by bravo-kernel** [comment]
first-name works perfect in (almost) all API consuming clients including javascript ones so I would say... adopt kebab-case.

**Comment by thiagoreri** [comment]
I know the subject here is not vues, but vuejs does not accept first-name property in object, is there any way to solve this problem?

**Comment by bravo-kernel** [comment]
To solve:

1. configure the listener to use one of the supported CakePHP inflections found at  https://book.cakephp.org/3.0/en/core-libraries/inflector.html. E.g.

    ```php
    public function initialize()
    {
      parent::initialize();
      $this->Crud->config('listeners.jsonApi.inflect', 'underscore');
    }
    ```
2. then make the code work
3. submit a PR for the fix

**Comment by thiagoreri** [comment]
What would PR be? I'm a beginner, sorry.

**Comment by bravo-kernel** [comment]
Pull Request containing all your fixes to solve this problem. https://help.github.com/articles/about-pull-requests/

**Comment by thiagoreri** [comment]
there is a possibility that the integer type attributes of the json object are returned as string?

**Comment by bravo-kernel** [comment]
Reopening as this is a valid issue.

**Comment by josegonzalez** [comment]
@bravo-kernel note: setting that value as you mentioned seems to skip all the `dasherize` stuff.

**Comment by bravo-kernel** [comment]
I know it works at least a little but I am unsure it is applied/ignored everywhere. I remember having notes on it needing to be finished. One more reason to get that test-overhaul done.

**Comment by bravo-kernel** [comment]
I know it works at least a little but I am unsure it is applied/ignored everywhere. I remember having notes on it needing to be finished. One more reason to get that test-overhaul done.

**Comment by RKostadinov** [comment]
@bravo-kernel  Do you happen to have a status update on this issue? We are using the plugin and underscores are used everywhere in our application and it seems to be partly working with underscores, but sometimes we get a Internal Server Error 500 because of that dasherizing. In order to get it working we should have our attributes sent to the server with this structure:  `one-two_three` as `one-two` is the name of the resource, which is not consistent with everything else.

**Comment by bravo-kernel** [comment]
@RKostadinov since my time is very limited I have to choose between what chores to pick up. Unfortunately this one is not high on my list so in all honesty, I am waiting for someone who is willing to put in the work to PR this.

Should not be too much work, I have been told it "almost fully" works.

**Comment by dakota** [comment]
This is no longer an issue in the latest RC.
