### ISSUE TITLE
relationship

### ISSUE THREAD

**Issue by thiagoreri** [FriendsOfCake/crud-json-api#56]
How to save hasOne and belongsTo relationships?

**Comment by bravo-kernel** [comment]
Good question which has led to:

- [Updated documentation with an example](https://crud-json-api.readthedocs.io/en/latest/api-usage/creating-resources.html)
- [Various examples of valid JsonApiRequestBodies required to create these kind of relationships](https://github.com/FriendsOfCake/crud-json-api/tree/master/tests/Fixture/JsonApiRequestBodies/CreatingResources)
- [Integration test using the above fixtures](https://github.com/FriendsOfCake/crud-json-api/blob/master/tests/TestCase/Integration/JsonApi/CreatingResourcesIntegrationTest.php)

Hope this helps you. If you have any more questions feel free to ask.
