### ISSUE TITLE
Upgrade to neomerx/jsonapi ^2.0

### ISSUE THREAD

**Issue by bravo-kernel** [FriendsOfCake/crud-json-api#57]
We are currently using ^1.0 which is not the latest/current version.

**Comment by bravo-kernel** [comment]
Putting this on-hold as it requires `"php": ">=7.1.0",`

**Comment by bravo-kernel** [comment]
Reminder to wait for Cake 4.x

**Comment by dakota** [comment]
`neomerx/jsonapi` version 3.0 has been released.

Any specific reason to wait for CakePHP 4.x? Changing this library to be `>7.1` is not a bad thing, and can be done separately to CakePHP 4.x support.

**Comment by bravo-kernel** [comment]
1. No other reason than me not doing any development atm. 
2. At the time I was under the assumption Cake 4.x was required, was probably wrong ;)

**Comment by dakota** [comment]
I'm busy on a Json:API project again, so, maybe I'll have some time :)

**Comment by bravo-kernel** [comment]
Any PR, help or even sign-of-life is more than welcome. I felt a bit abandoned to be honest.
