### ISSUE TITLE
[RFC] Support existing hasMany relationships for PATCH requests

### ISSUE THREAD

**Issue by bravo-kernel** [FriendsOfCake/crud-json-api#73]
Integration tests have proven that crud-json-api PATCH requests are currently not handling `hasMany` relationships as decribed by the [JSON API specification](http://jsonapi.org/format/#crud-updating-resource-relationships).

Thus far I see two possible solutions but would appreciate feedback on this. 

### What are we talking about?

JSON API allows PATCH requests to provide `hasMany` relationships for the main resource as long as they match the following criteria:

- they MUST be existing relationships
- `id` MUST be present
- `type` MUST be present

When provided during a PATCH, these `hasMany` relationships:

- crud-json-api MUST replace all other existing `hasMany` relationships for this Resource

### How does the client know which `ids` to pass?

The client has to pre-fetch the relationship data using either one of the following three options:

1. query the existing Resource using the `?include=capital-cities` query parameter
2. query the relationships link specific for the existing Resource (e.g. `/countries/1/capital-cities`)
3. query the relationships endpoint directly with a search query (e.g. `/capital-cities?country-id=1`

> option 2 currently not implemented

### Solution 1

We choose not to support this functionality.

> "A server **MAY** reject an attempt to do a full replacement of a to-many relationship. In such a case, the server **MUST** reject the entire update, and return a 403 Forbidden response."

- PRO: nothing to implement
- CON: this seems expected functionality
- CON: the 403 message might be confusing (e.g. in cases where the API is not even using Auth)

### Solution 2

Implement as described by the spec.

- PRO: plugin behaves as expected, better support (explainable)
- CON: requires heavy backend magic before applying:
   - are passed all `ids` valid (do they exist)?
   - delete all other existing relationships
   - report validation errors

Suggestions on how this could work are more than welcome.

**Comment by dakota** [comment]
Regarding Solution 2's Con, can probably be 99% (if not 100%) implementing by simply enforcing the replace save strategy for has many (https://book.cakephp.org/3.0/en/orm/associations.html#hasmany-associations)

**Comment by bravo-kernel** [comment]
Thank you @dakota, never knew about that strategy but it looks a perfect fit. I will investigate.

**Comment by davizxtr** [comment]
hi @bravo-kernel  sorry for not having answered before.
I've had a lot of trouble at work.
I have tried what you updated in master.

> trying to create new (hasMany) relationships will now throw a BadRequestException (as side-posting is not supported by JSON API 1.0)

![image](https://user-images.githubusercontent.com/37248385/40743175-181075d6-6451-11e8-83fc-b06ff1f5825d.png)

**Comment by bravo-kernel** [comment]
@davizxtr no worries, and the test-request preceeded this ticket. I will let you know once the final solution is in place.

**Comment by bravo-kernel** [comment]
@dakota @josegonzalez I managed to implement a working solution using the `replace` strategy :)

Before I round up tests etc, would you please look at the commit above (for any no-gos).

Much obliged

**Comment by bravo-kernel** [comment]
@davizxtr I have implemented side-patching for (existing) belongsTo and hasMany relationships in #72. Could you try that PR to see if it works for you.

Disclaimer: side-patching NOT side-posting !

**Comment by bravo-kernel** [comment]
Closing as PR #72 is now open
