### ISSUE TITLE
404 and pagination issues

### ISSUE THREAD

**Issue by frogjimjaff** [FriendsOfCake/crud-json-api#75]
'm adding a REST API onto an existing cakephp codebase.

It is working as I expect. I hit /api/v1/contacts/12312 and get json data back for contact 12312. If put an id of a contact that doesn't exist then I get the html 404 page error rather than json.

This happens internally on the contacts->get($id) line.

In the api app controller I have

`public function initialize()
    {

        parent::initialize();
        $this->loadComponent('RequestHandler');
        $this->loadComponent('Crud.Crud', [
            'actions' => [
                'Crud.Index',
                'Crud.View',
                'Crud.Add',
                'Crud.Edit',
                'Crud.Delete'
            ],
            'listeners' => [
                'CrudJsonApi.JsonApi',
                'CrudJsonApi.Pagination', // Pagination != ApiPagination
                'Crud.ApiQueryLog',

            ],
            'Error' => [
                'errorLevel' => E_ALL,
                'exceptionRenderer' => 'CrudJsonApi\Error\JsonApiExceptionRenderer',
                'skipLog' => [],
                'log' => true,
                'trace' => true,
        ],
        ]);

        $this->Crud->config(['listeners.jsonApi.exceptionRenderer' => 'CrudJsonApi\Error\JsonApiExceptionRenderer']);

        $this->setJsonResponse();
    }

public function beforeRender(Event $event)
{
    $this->RequestHandler->renderAs($this, 'json');
    $this->response->type('application/json');
    $this->set('_serialize', true);
}`

 thought using the JsonApiExceptionRenderer 404 errors would be handled with json output.

Also the Pagination works but the Pagination data isnt returned with the response...

```
{
  "viewVar": "crmContacts",
  "crmContacts": [
    {
      "id": 1,
      "lastname": "testname1"
    },
    {
      "id": 2,
      "lastname": "smith"
    }
  ],
  "success": true
}

```

Any ideas? thanks

**Comment by bravo-kernel** [comment]
The response looks non **JSON API** to me. Could you try disabling your `beforeRender()` logic as it is:

- most likely interfering with crud-json-api
- totally unneeded, crud-json-api handles all that for you

Lastly, make sure you are sending the correct JSON API Request Header as described [here](https://crud-json-api.readthedocs.io/en/latest/api-usage/fetching-resources.html). Without that header nothing crud-json-api will ever happen.

**Comment by frogjimjaff** [comment]
Hi Thanks I've taken out my beforerender and checked the header which is correct.

But with my beforerender disabled I get a html  Error: Missing Template  error page

its hitting the correct controllers etc so Im not sure what the issue is. 


In my routes i have $routes->setExtensions(['json']);  is that needed? 

  ```

  //valid api routes    
        $API_RESOURCES = [
          'CrmContacts',
          'CrmEvents'
        ];


 Router::prefix('api', function ($routes) {
        $routes->setExtensions(['json']);
        $routes->prefix('v1', function ($routes) {
            
      

        foreach ($API_RESOURCES as $apiResource) {



            $routes->resources($apiResource, [
                'inflect' => 'dasherize'
            ]);
        }
            
  
            
            
        });
     });
    
```

**Comment by frogjimjaff** [comment]
Sorry my mistake I had the content type set not the accept to application/vnd.api+json

**Comment by bravo-kernel** [comment]
IMO you should start re-checking your existing setup using the (exact) documented crud-json-api steps. You ONLY need what is described there.

**Comment by frogjimjaff** [comment]
Thank you im not getting proper json back with errors etc..

If I have my own index method how do I return the data so I dont get 
"errors": [
    {
      "code": "500",
      "title": "Internal Server Error",
      "detail": "Template file \"Api/V1/CrmContacts/index.ctp\" is missing."
    }
  ],

**Comment by bravo-kernel** [comment]
Content-type is not required for GET requests, only for PATCH/POST.

However, this is a bug tracker and not a help forum. I think you should join the CakePHP slack channel and ask for help there. There are a lot of people willing to help you on your way there.

Closing but feel free to add the solution once you have figured it out to perhaps help future users.

**Comment by frogjimjaff** [comment]
OK sorry thanks for your help
