### ISSUE TITLE
Date returning format

### ISSUE THREAD

**Issue by thiagoreri** [FriendsOfCake/crud-json-api#76]
**Even though I make the settings:**

config/app.php check:
'defaultLocale' => env('APP_DEFAULT_LOCALE', 'pt_BR'),
'defaultTimezone' => env('APP_DEFAULT_TIMEZONE', 'America/Sao_Paulo'),

config/bootstrap.php 
use Cake\I18n\I18n;
I18n::setLocale('pt-BR');

Type::build('time')->useImmutable();
Type::build('date')->useImmutable();
Type::build('datetime')->useImmutable();
Type::build('timestamp')->useImmutable();

Type::build('date')->useLocaleParser()->setLocaleFormat('dd/MM/yyyy');
Type::build('datetime')->useLocaleParser()->setLocaleFormat('dd/MM/yyyy HH:mm');
Type::build('timestamp')->useLocaleParser()->setLocaleFormat('dd/MM/yyyy HH:mm');
Type::build('decimal')->useLocaleParser();
Type::build('float')->useLocaleParser();

**my dates return this way:**

2018-01-01T00:00:00+00:00

**when I need them to return this way:**

2017-12-27T00:00:00.000Z

**Comment by lorenzo** [comment]
Add this to your bootstrap or before the action you want to make this format be returned:

```php
\Cake\I18n\FrozenTime::setJsonEncodeFormat("yyyy-MM-dd'T'HH:mm:ss'Z'");
\Cake\I18n\FrozenDate::setJsonEncodeFormat('yyyy-MM-dd');
```

**Comment by bravo-kernel** [comment]
Thanks @lorenzo, I will add this to the docs as well.  💯

**Comment by bravo-kernel** [comment]
https://github.com/FriendsOfCake/crud-json-api/pull/77
