### ISSUE TITLE
API specs

### ISSUE THREAD

**Issue by dereuromark** [FriendsOfCake/crud-json-api#8]
There are currently some inconsistencies and possible var conflicts due to not following the standard:
```
A document MUST contain at least one of the following top-level members:
- data: the document’s “primary data”
- errors: an array of error objects
- meta: a meta object that contains non-standard meta-information.

The members data and errors MUST NOT coexist in the same document.
```

Currently:
```
{
    "message": "2 validation errors occurred",
    "url": "/wheels.json",
    "code": 422,
    "file": "/home/vagrant/Apps/rest-cake.local/vendor/friendsofcake/crud/src/Listener/ApiListener.php",
    "line": 181
}
```
when posting to /wheels.json

I would have expected
```
{
    "errors": {
        "wheel": {
            "name": "Missing"
        },
    },
    "success": false
    ...
}
```
for error case 

and
```
{
    "data": {
        "wheel": {
            "description": "3nd descr"
        },
    },
    "success": true
    ...
}
```
for success case

Also imagine, we would save successes and success entities or alike
Those would conflict then, as well.

**Comment by dereuromark** [comment]
OK, part of it is resolved with https://github.com/FriendsOfCake/crud-json-api/pull/11

The docs should probably point out the importance of the right error/exception handler setup.

**Comment by bravo-kernel** [comment]
@dereuromark we could add some note to https://crud-json-api.readthedocs.io/en/latest/preface/setup.html#exception-handler.

**Comment by bravo-kernel** [comment]
Validation errors should look (exactly) like the example at https://crud-json-api.readthedocs.io/en/latest/usage/errors-exceptions.html#validation-errors.
