### ISSUE TITLE
Return incorrect

### ISSUE THREAD

**Issue by thiagoreri** [FriendsOfCake/crud-json-api#82]
When I use the same relationship with different names, the two objects are returned as PessoaDestinatario. 

$this->belongsTo('PessoaDestinatario', [
             'className' => 'Pessoa',
             'foreignKey' => 'pessoa_destinatario_id',
             'joinType' => 'INNER',
         ]);
         $this->belongsTo('PessoaTransportadora', [
             'className' => 'Pessoa',
             'foreignKey' => 'pessoa_transportadora_id',
             'joinType' => 'INNER',
         ]);

**Comment by bravo-kernel** [comment]
This is the method responsible for creating the `belongsTo` relationship nodes. Can you try solving your issue there?

https://github.com/FriendsOfCake/crud-json-api/blob/master/src/Listener/JsonApiListener.php#L590

**Comment by thiagoreri** [comment]
He did not go through this method. It falls within this condition

if (! empty ($ event-> getSubject () -> query-> getContain ())) {
  $this->_ ControllerHasSetContain = true;

  return null;
}

**Comment by dakota** [comment]
Closing as stale. Please reopen if this is still an issue.
