### ISSUE TITLE
DynamicEntitySchema::getAttributes() needs to work with an array of foreign keys as well.

### ISSUE THREAD

**Issue by baseer** [FriendsOfCake/crud-json-api#86]
https://github.com/FriendsOfCake/crud-json-api/blob/5ecd43b5af7b6422b04bc12e1b047e9fe7c981a8/src/Schema/JsonApi/DynamicEntitySchema.php#L107-L110

Line 109 throws an error because `unset()` is expecting `$foreignKey` to be a key and not an array. But we can see here that we can actually have an array of `$foreignKeys`: https://book.cakephp.org/3.0/en/orm/associations.html#hasmany-associations. Even though it is in the hasMany section of Cake, having an array of `$foreignKeys` applies to the belongsTo section as well.

It's necessary for me to use an array of foreign keys because I'm working with an old db that didn't have this part designed properly.

Currently I have modified the block to support an array of foreign keys:

       if ($association->type() === Association::MANY_TO_ONE) {
           $foreignKeys = $association->getForeignKey();
           if (is_array($foreignKeys)){
               $attributes = array_diff_key($attributes, array_flip($foreignKeys));
           }
           else {
               unset($attributes[$foreignKeys]);
           }
       }

**Comment by dakota** [comment]
CrudJsonApi doesn't currently support composite keys, feel free to submit a PR though!
