### ISSUE TITLE
"'type' is a reserved keyword and cannot be used as attribute name in type "controller"

### ISSUE THREAD

**Issue by dkruchok** [FriendsOfCake/crud-json-api#91]
I experience such an error because I have column "**type**" in my table and I don't want to rename it.
How I can avoid this? 

Maybe I can change the name of the property with the entity, but how I can do it only for API request?
Or maybe it's possible to change with DynamicEntitySchema::getAttributes() then rename **type** property. Also how I can do it for a plugin?

Tried to create Shema file in plugin/src/Schema/JsonApi/EventsTicketSchema.php
But looks like it doesn't see it.

namespace plugin\Schema\JsonApi;
plugin.EventsTickets - table
EventsTicket  - entity

```
"errors": [
	{
		"code": "500",
		"title": "Internal Server Error",
		"detail": "'type' is a reserved keyword and cannot be used as attribute name in type 'events-tickets'"
	}
],
```

**Comment by bravo-kernel** [comment]
Like the error message clearly states... you cannot use `type` as it is a keyword reserved by JSON:API.

You can find more background information here. https://jsonapi.org/format/#document-resource-objects
