### ISSUE TITLE
Incorrect pagination links while doing custom action

### ISSUE THREAD

**Issue by ernestngugi** [FriendsOfCake/crud-json-api#92]
While fetching results from a custom action, the pagination links generated match up to the index action (http://.../api/RstTblitems?page=1) instead of the custom action (http://.../api/RstTblitems/filter?sortBy=wine&page=1 or something close to that)

Cakephp v3.6
Crud Json Api v0.4.0 
![image](https://user-images.githubusercontent.com/13958553/49581360-b561d900-f962-11e8-9d3e-b4c111e20f62.png)

**Comment by dakota** [comment]
Closing as stale. Please reopen if this is still an issue.
