### ISSUE TITLE
BelongsTo and route not found error MissingRouteException

### ISSUE THREAD

**Issue by frogjimjaff** [FriendsOfCake/crud-json-api#94]
Hi

I'm getting an error with when doing a PATCH to update one field.

The model has a number of belongsTo relationships and if I comment those out the code works and updates the data with no errors and returns a 200 code. 

If the belongsTo code is in place the data is updated but an error is returned.

The data I send is 

{  
"data": {
    "type": "crmEvents",
    "id": "1806",
    "attributes": {
      "title": "My new name now"
    }
  }
}

The belongsTo(s) look like this :

   $this->belongsTo('Creator', [
            'className' => 'CrmUsers',
            'foreignKey' => 'admin_created_by',
        ]);

and the error message I get is :
"code": "404",
      "title": "Not Found",
      "detail": "A route matching \"array (\n  'controller' => 'Creator',\n  '_method' => 'GET',\n  'action' => 'view',\n  0 => 82,\n  'prefix' => 'api/v1',\n  'plugin' => NULL,\n  '_ext' => NULL,\n)\" could not be found."
    }

Why is it looking for a route for Creator?  There isn't one in the system

Thanks

**Comment by geoidesic** [comment]
Because it has to be able to look up creator, which it cannot do if there's no route. See this: https://crud-json-api.readthedocs.io/en/latest/additional-information/common-issues.html#missing-routes

**Comment by dakota** [comment]
Closing as stale. Please reopen if this is still an issue.
