### ISSUE TITLE
Dealing with CSRF middleware

### ISSUE THREAD

**Issue by mosesliao** [FriendsOfCake/crud-json-api#96]
I keep getting this CSRF token mismatch via an api call. Is there a way to handle it in a graceful way? I heard that disabling it is not advisable. I am using this library plus this code

```
    public function add()
    {
        $location = $this->Locations->newEntity();
        if ($this->request->is('post')) {
            $location->code = $this->request->getData('code');
            $location->name = $this->request->getData('name');
            if ($this->Locations->save($location)) {
              $this->set([
                'success' => true,
                '_serialize' => ['success']
              ]);
            }
        }
    }
```
<img width="1124" alt="Screenshot 2019-03-29 at 9 26 37 PM" src="https://user-images.githubusercontent.com/317035/55235829-68837480-5269-11e9-908f-59906e82d4f7.png">

**Comment by ADmad** [comment]
Just don't use the CSRF middleware for API URLs. Stateless API can't suffer from CSRF.
