### ISSUE TITLE
Cannot use Crud\Core\Objec

### ISSUE THREAD

**Issue by BGFR** [FriendsOfCake/crud-json-api#99]
I was not using the api for long time and then we swtiched to php 7.2 It shows the error below. OS is Ubuntu 14.04.6 I am worse than a beginner and have no idea where to start from. I'd be thankful if somene tells me where to start from.

composer.json looks like this:

> "require": {
>     "php": ">=5.5.9", 
>     "cakephp/cakephp": "~3.2",
>     "mobiledetect/mobiledetectlib": "2.*",
>     "cakephp/migrations": "~1.0",
>     "cakephp/plugin-installer": "*",
>     "friendsofcake/crud":"~4.0"

> Fatal error: Cannot use Crud\Core\Object as Object because 'Object' is a special class name in /www/htdocs/w0555555e/api.website.com/vendor/friendsofcake/crud/src/Listener/BaseListener.php on line 4

**Comment by saeideng** [comment]
you have to update your vendor if you want to use php7.2 
https://github.com/FriendsOfCake/crud/commit/0df5ee4dc9

**Comment by BGFR** [comment]
Ok I did this. Now error is 

> Warning (2): count(): Parameter must be an array or an object that implements Countable [CORE/src/Database/QueryCompiler.php, line 128]
> Warning (2): count() [<a href='http://php.net/function.count'>function.count</a>]: Parameter must be an array or an object that implements Countable [CORE/src/Database/QueryCompiler.php, line 128]

I accessed via SSH and ran command `composer update` and response is `bash: composer: command not found`

**Comment by bravo-kernel** [comment]
This is not a help forum. Please refer to the CakePHP documentation (e.g. [on Composer](https://book.cakephp.org/3.0/en/installation.html#installing-composer)) or turn to the Slack channel for help. There are a lot of smart(er) people out there willing to help you out.

**Comment by BGFR** [comment]
Thank you! Sorry for that.

**Comment by bravo-kernel** [comment]
No problem, would you please close this ticket if you revolve your issue?
